name: Test Data Analysis And Visualization Notebooks

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Notebook tests
        shell: bash -l {0}
        run: |
          python -m pytest --nbval --nbval-lax jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/
